services:
  authentication_microservice_db:
    image: mysql
    restart: always
    ports:
      - "4000:3306"
    environment:
      - MYSQL_DATABASE=c2s_technical_challenge_users
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - c2s-technical-challenge-main-task-system_main-task-system-network

  authentication_microservice_db_test:
    image: mysql
    restart: always
    ports:
      - "8000:3306"
    environment:
      - MYSQL_DATABASE=c2s_technical_challenge_users_test
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - c2s-technical-challenge-main-task-system_main-task-system-network

  authentication_microservice_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - ./:/rails
    ports:
      - "5000:5000"
    depends_on:
      - authentication_microservice_db
      - authentication_microservice_db_test
    networks:
      - c2s-technical-challenge-main-task-system_main-task-system-network

networks:
  c2s-technical-challenge-main-task-system_main-task-system-network:
    external: true
