services:
  db:
    image: mysql
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MYSQL_DATABASE=c2s_technical_challenge_users
      - MYSQL_ROOT_PASSWORD=root

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - ./:/rails
    ports:
      - "5000:5000"
    depends_on:
      - db
